### ISSUE TITLE
vst3

### ISSUE THREAD

**Issue by AdmiralJensen** [d3NNEb/NeuralAmpModeler-#1]
Today I downloaded and replaced the vst3 from 3/31 with the same one (I noticed afterwards, so nothing should have changed) and when I launched REAPER the NAM and IR fields only have the directory used, not the file.   This causes many problems, most glaring is I haven't a clue what files were selected. 
![image](https://user-images.githubusercontent.com/569662/230629967-9a98e78d-81e8-496e-a187-752a719512b6.png)
(As an aside, not a new issue yet, but where is the online db used to select images?  It isn't like you show in the youtube video.)

**Comment by AdmiralJensen** [comment]
Today I loaded an rpp in REAPER and every setting in NAM was reset.  I gotta go with another build :(

**Comment by highway11** [comment]
I have the same issue. The VST is not saving the selected NAM or IR file settings when loading a Reaper project. It only shows the folder last used.

**Comment by d3NNEb** [comment]
thanks everyone @AdmiralJensen, @fichl, @highway11 for the feedback, the issues are now fixed!

**Comment by AdmiralJensen** [comment]
Thank You very much!
